server.port=${PORT:8080}

spring.datasource.url=${mysql://root:pFGiOmtMgElHqPQtCWMlURKriwMRnuMl@hayabusa.proxy.rlwy.net:40619/railway}
spring.datasource.username=${root}
spring.datasource.password=${pFGiOmtMgElHqPQtCWMlURKriwMRnuMl}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.fail-on-empty-beans=false
