# ================================
# SERVER CONFIG
# ================================
server.port=${PORT:8080}

# ================================
# POSTGRESQL DATABASE CONFIG
# ================================
spring.datasource.url=jdbc:postgresql://ep-green-dew-ax1f2nd7-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QVDNKi3r9Jge
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / HIBERNATE CONFIG
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================================
# JACKSON
# ================================
spring.jackson.serialization.fail-on-empty-beans=false